apiVersion: apps/v1
kind: Deployment
metadata:
  {{- with .Values.deploymentAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ include "pulumi-kubernetes-operator.fullname" . }}-controller-manager
  labels:
  {{- include "pulumi-kubernetes-operator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: {{ default "RollingUpdate" .Values.deploymentStrategy }}
  selector:
    matchLabels:
    {{- include "pulumi-kubernetes-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
      {{- include "pulumi-kubernetes-operator.selectorLabels" . | nindent 8 }}
      {{- if .Values.podLabels }}
        {{ toYaml .Values.podLabels | indent 8 }}
      {{- end }}
    spec:
      containers:
      {{- if .Values.extraSidecars }}
      {{- toYaml .Values.extraSidecars  | nindent  8 }}
      {{- end}}
      - name: manager
        args:
        - /manager
        - --leader-elect
        - --health-probe-bind-address=:8081
        - --metrics-bind-address=:8383
        - --program-fs-adv-addr={{ include "pulumi-kubernetes-operator.advertisedAddress" . }}:80
        - --zap-log-level={{ .Values.controller.logLevel }}
        - --zap-time-encoding=iso8601
        env:
        {{- if .Values.extraEnv }}
        {{- toYaml .Values.extraEnv  | nindent 8 }}
        {{- end }}
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        ports:
        - containerPort: 8383
          name: http-metrics
          protocol: TCP
        - containerPort: 9090
          name: http-fileserver
          protocol: TCP
        {{- if .Values.extraPorts }}
        {{- toYaml .Values.extraPorts  | nindent 8 }}
        {{- end }}
        image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        {{- if .Values.securityContext }}
        securityContext:
        {{- toYaml .Values.securityContext | nindent 12 }}
        {{- end }}
        {{- if .Values.resources }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        {{- end }}
        {{- with .Values.extraVolumeMounts }}
        volumeMounts:
        {{- toYaml . | nindent 8 }}
        {{- end }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "pulumi-kubernetes-operator.serviceAccountName" . }}
      {{- if .Values.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      {{- end }}
      {{- if .Values.podSecurityContext }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.initContainers  }}
      initContainers:
      {{- with .Values.initContainers }}
        {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- end }}
      {{- with .Values.extraVolumes }}
      volumes:
        {{- toYaml . | nindent 6 }}
      {{- end }}
