{{- if and .Values.rbac.create .Values.rbac.createClusterAggregationRoles }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "pulumi-kubernetes-operator.fullname" . }}-edit
  labels:
  {{- include "pulumi-kubernetes-operator.labels" . | nindent 4 }}
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
rules:
- apiGroups:
  - pulumi.com
  - auto.pulumi.com
  resources:
  - '*'
  verbs:
  - create
  - delete
  - deletecollection
  - patch
  - update
{{- end }}
