{{- if and .Values.rbac.create .Values.rbac.createRole }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "pulumi-kubernetes-operator.fullname" . }}-controller-manager
  labels:
  {{- include "pulumi-kubernetes-operator.labels" . | nindent 4 }}
rules:
  {{- if .Values.rbac.extraRules }}
    {{- toYaml .Values.rbac.extraRules | nindent 2 }}
  {{- end }}
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - pods
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - auto.pulumi.com
  resources:
  - updates
  - workspaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - auto.pulumi.com
  resources:
  - updates/finalizers
  - workspaces/finalizers
  verbs:
  - update
- apiGroups:
  - auto.pulumi.com
  resources:
  - updates/status
  - workspaces/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - auto.pulumi.com
  resources:
  - workspaces/rpc
  verbs:
  - use
- apiGroups:
  - pulumi.com
  resources:
  - programs
  - stacks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pulumi.com
  resources:
  - programs/finalizers
  - stacks/finalizers
  verbs:
  - update
- apiGroups:
  - pulumi.com
  resources:
  - programs/status
  - stacks/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - source.toolkit.fluxcd.io
  resources:
  - buckets
  - gitrepositories
  - ocirepositories
  verbs:
  - get
  - list
  - watch
{{- end }}
