apiVersion: v1
kind: Service
metadata:
  name: {{ include "pulumi-kubernetes-operator.fullname" . }}
  labels:
  {{- include "pulumi-kubernetes-operator.labels" . | nindent 4 }}
  {{- with .Values.serviceAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  ports:
    - name: http-fileserver
      port: 80
      protocol: TCP
      targetPort: http-fileserver
    - name: http-metrics
      port: 8383
      targetPort: http-metrics
      protocol: TCP
  selector:
    {{- include "pulumi-kubernetes-operator.selectorLabels" . | nindent 4 }}
