apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "pulumi-kubernetes-operator.fullname" . }}-token-request-role
  labels:
  {{- include "pulumi-kubernetes-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - serviceaccounts/token
  resourceNames:
  - {{ include "pulumi-kubernetes-operator.serviceAccountName" . }}
  verbs:
  - create
