// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.Pulumi.V1Alpha1
{

    [OutputType]
    public sealed class StackStatus
    {
        /// <summary>
        /// LastUpdate contains details of the status of the last update.
        /// </summary>
        public readonly Pulumi.Kubernetes.Types.Outputs.Pulumi.V1Alpha1.StackStatusLastUpdate LastUpdate;
        /// <summary>
        /// Outputs contains the exported stack output variables resulting from a deployment.
        /// </summary>
        public readonly ImmutableDictionary<string, ImmutableDictionary<string, object>> Outputs;

        [OutputConstructor]
        private StackStatus(
            Pulumi.Kubernetes.Types.Outputs.Pulumi.V1Alpha1.StackStatusLastUpdate lastUpdate,

            ImmutableDictionary<string, ImmutableDictionary<string, object>> outputs)
        {
            LastUpdate = lastUpdate;
            Outputs = outputs;
        }
    }
}
