[tools]
golangci-lint = "1.58.1"
etcd = "3.5.16"
protoc = "29.3"
protoc-gen-go = "1.36.4"
protoc-gen-go-grpc = "1.5.1"
kubebuilder = "4.2.0"
envsubst = "1.4.2"

[settings]
experimental = true    # Enable Go backend.
