coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true
ignore:
  - "**/zz_generated.deepcopy.go"
  - "**/*.pb.go"
  - "operator/internal/apply/**/*.go"
