// Copyright 2016-2025, Pulumi Corporation.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// ArtifactApplyConfiguration represents a declarative configuration of the Artifact type for use
// with apply.
type ArtifactApplyConfiguration struct {
	Path           *string           `json:"path,omitempty"`
	URL            *string           `json:"url,omitempty"`
	Revision       *string           `json:"revision,omitempty"`
	Digest         *string           `json:"digest,omitempty"`
	LastUpdateTime *metav1.Time      `json:"lastUpdateTime,omitempty"`
	Size           *int64            `json:"size,omitempty"`
	Metadata       map[string]string `json:"metadata,omitempty"`
}

// ArtifactApplyConfiguration constructs a declarative configuration of the Artifact type for use with
// apply.
func Artifact() *ArtifactApplyConfiguration {
	return &ArtifactApplyConfiguration{}
}

// WithPath sets the Path field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Path field is set to the value of the last call.
func (b *ArtifactApplyConfiguration) WithPath(value string) *ArtifactApplyConfiguration {
	b.Path = &value
	return b
}

// WithURL sets the URL field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the URL field is set to the value of the last call.
func (b *ArtifactApplyConfiguration) WithURL(value string) *ArtifactApplyConfiguration {
	b.URL = &value
	return b
}

// WithRevision sets the Revision field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Revision field is set to the value of the last call.
func (b *ArtifactApplyConfiguration) WithRevision(value string) *ArtifactApplyConfiguration {
	b.Revision = &value
	return b
}

// WithDigest sets the Digest field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Digest field is set to the value of the last call.
func (b *ArtifactApplyConfiguration) WithDigest(value string) *ArtifactApplyConfiguration {
	b.Digest = &value
	return b
}

// WithLastUpdateTime sets the LastUpdateTime field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LastUpdateTime field is set to the value of the last call.
func (b *ArtifactApplyConfiguration) WithLastUpdateTime(value metav1.Time) *ArtifactApplyConfiguration {
	b.LastUpdateTime = &value
	return b
}

// WithSize sets the Size field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Size field is set to the value of the last call.
func (b *ArtifactApplyConfiguration) WithSize(value int64) *ArtifactApplyConfiguration {
	b.Size = &value
	return b
}

// WithMetadata puts the entries into the Metadata field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Metadata field,
// overwriting an existing map entries in Metadata field with the same key.
func (b *ArtifactApplyConfiguration) WithMetadata(entries map[string]string) *ArtifactApplyConfiguration {
	if b.Metadata == nil && len(entries) > 0 {
		b.Metadata = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.Metadata[k] = v
	}
	return b
}
