// Copyright 2016-2025, Pulumi Corporation.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// CustomTimeoutsApplyConfiguration represents a declarative configuration of the CustomTimeouts type for use
// with apply.
type CustomTimeoutsApplyConfiguration struct {
	Create *string `json:"create,omitempty"`
	Delete *string `json:"delete,omitempty"`
	Update *string `json:"update,omitempty"`
}

// CustomTimeoutsApplyConfiguration constructs a declarative configuration of the CustomTimeouts type for use with
// apply.
func CustomTimeouts() *CustomTimeoutsApplyConfiguration {
	return &CustomTimeoutsApplyConfiguration{}
}

// WithCreate sets the Create field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Create field is set to the value of the last call.
func (b *CustomTimeoutsApplyConfiguration) WithCreate(value string) *CustomTimeoutsApplyConfiguration {
	b.Create = &value
	return b
}

// WithDelete sets the Delete field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Delete field is set to the value of the last call.
func (b *CustomTimeoutsApplyConfiguration) WithDelete(value string) *CustomTimeoutsApplyConfiguration {
	b.Delete = &value
	return b
}

// WithUpdate sets the Update field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Update field is set to the value of the last call.
func (b *CustomTimeoutsApplyConfiguration) WithUpdate(value string) *CustomTimeoutsApplyConfiguration {
	b.Update = &value
	return b
}
