// Copyright 2016-2025, Pulumi Corporation.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	apiextensionsv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
)

// OptionsApplyConfiguration represents a declarative configuration of the Options type for use
// with apply.
type OptionsApplyConfiguration struct {
	AdditionalSecretOutputs []string                          `json:"additionalSecretOutputs,omitempty"`
	Aliases                 []string                          `json:"aliases,omitempty"`
	CustomTimeouts          *CustomTimeoutsApplyConfiguration `json:"customTimeouts,omitempty"`
	DeleteBeforeReplace     *bool                             `json:"deleteBeforeReplace,omitempty"`
	DependsOn               []apiextensionsv1.JSON            `json:"dependsOn,omitempty"`
	IgnoreChanges           []string                          `json:"ignoreChanges,omitempty"`
	Import                  *string                           `json:"import,omitempty"`
	Parent                  *apiextensionsv1.JSON             `json:"parent,omitempty"`
	Protect                 *bool                             `json:"protect,omitempty"`
	Provider                *apiextensionsv1.JSON             `json:"provider,omitempty"`
	Providers               map[string]apiextensionsv1.JSON   `json:"providers,omitempty"`
	Version                 *string                           `json:"version,omitempty"`
}

// OptionsApplyConfiguration constructs a declarative configuration of the Options type for use with
// apply.
func Options() *OptionsApplyConfiguration {
	return &OptionsApplyConfiguration{}
}

// WithAdditionalSecretOutputs adds the given value to the AdditionalSecretOutputs field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the AdditionalSecretOutputs field.
func (b *OptionsApplyConfiguration) WithAdditionalSecretOutputs(values ...string) *OptionsApplyConfiguration {
	for i := range values {
		b.AdditionalSecretOutputs = append(b.AdditionalSecretOutputs, values[i])
	}
	return b
}

// WithAliases adds the given value to the Aliases field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Aliases field.
func (b *OptionsApplyConfiguration) WithAliases(values ...string) *OptionsApplyConfiguration {
	for i := range values {
		b.Aliases = append(b.Aliases, values[i])
	}
	return b
}

// WithCustomTimeouts sets the CustomTimeouts field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CustomTimeouts field is set to the value of the last call.
func (b *OptionsApplyConfiguration) WithCustomTimeouts(value *CustomTimeoutsApplyConfiguration) *OptionsApplyConfiguration {
	b.CustomTimeouts = value
	return b
}

// WithDeleteBeforeReplace sets the DeleteBeforeReplace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DeleteBeforeReplace field is set to the value of the last call.
func (b *OptionsApplyConfiguration) WithDeleteBeforeReplace(value bool) *OptionsApplyConfiguration {
	b.DeleteBeforeReplace = &value
	return b
}

// WithDependsOn adds the given value to the DependsOn field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the DependsOn field.
func (b *OptionsApplyConfiguration) WithDependsOn(values ...apiextensionsv1.JSON) *OptionsApplyConfiguration {
	for i := range values {
		b.DependsOn = append(b.DependsOn, values[i])
	}
	return b
}

// WithIgnoreChanges adds the given value to the IgnoreChanges field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the IgnoreChanges field.
func (b *OptionsApplyConfiguration) WithIgnoreChanges(values ...string) *OptionsApplyConfiguration {
	for i := range values {
		b.IgnoreChanges = append(b.IgnoreChanges, values[i])
	}
	return b
}

// WithImport sets the Import field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Import field is set to the value of the last call.
func (b *OptionsApplyConfiguration) WithImport(value string) *OptionsApplyConfiguration {
	b.Import = &value
	return b
}

// WithParent sets the Parent field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Parent field is set to the value of the last call.
func (b *OptionsApplyConfiguration) WithParent(value apiextensionsv1.JSON) *OptionsApplyConfiguration {
	b.Parent = &value
	return b
}

// WithProtect sets the Protect field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Protect field is set to the value of the last call.
func (b *OptionsApplyConfiguration) WithProtect(value bool) *OptionsApplyConfiguration {
	b.Protect = &value
	return b
}

// WithProvider sets the Provider field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Provider field is set to the value of the last call.
func (b *OptionsApplyConfiguration) WithProvider(value apiextensionsv1.JSON) *OptionsApplyConfiguration {
	b.Provider = &value
	return b
}

// WithProviders puts the entries into the Providers field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Providers field,
// overwriting an existing map entries in Providers field with the same key.
func (b *OptionsApplyConfiguration) WithProviders(entries map[string]apiextensionsv1.JSON) *OptionsApplyConfiguration {
	if b.Providers == nil && len(entries) > 0 {
		b.Providers = make(map[string]apiextensionsv1.JSON, len(entries))
	}
	for k, v := range entries {
		b.Providers[k] = v
	}
	return b
}

// WithVersion sets the Version field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Version field is set to the value of the last call.
func (b *OptionsApplyConfiguration) WithVersion(value string) *OptionsApplyConfiguration {
	b.Version = &value
	return b
}
