// Copyright 2016-2025, Pulumi Corporation.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	apiextensionsv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
)

// ProgramSpecApplyConfiguration represents a declarative configuration of the ProgramSpec type for use
// with apply.
type ProgramSpecApplyConfiguration struct {
	Configuration map[string]ConfigurationApplyConfiguration `json:"configuration,omitempty"`
	Resources     map[string]ResourceApplyConfiguration      `json:"resources,omitempty"`
	Variables     map[string]apiextensionsv1.JSON            `json:"variables,omitempty"`
	Outputs       map[string]apiextensionsv1.JSON            `json:"outputs,omitempty"`
	Packages      map[string]string                          `json:"packages,omitempty"`
}

// ProgramSpecApplyConfiguration constructs a declarative configuration of the ProgramSpec type for use with
// apply.
func ProgramSpec() *ProgramSpecApplyConfiguration {
	return &ProgramSpecApplyConfiguration{}
}

// WithConfiguration puts the entries into the Configuration field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Configuration field,
// overwriting an existing map entries in Configuration field with the same key.
func (b *ProgramSpecApplyConfiguration) WithConfiguration(entries map[string]ConfigurationApplyConfiguration) *ProgramSpecApplyConfiguration {
	if b.Configuration == nil && len(entries) > 0 {
		b.Configuration = make(map[string]ConfigurationApplyConfiguration, len(entries))
	}
	for k, v := range entries {
		b.Configuration[k] = v
	}
	return b
}

// WithResources puts the entries into the Resources field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Resources field,
// overwriting an existing map entries in Resources field with the same key.
func (b *ProgramSpecApplyConfiguration) WithResources(entries map[string]ResourceApplyConfiguration) *ProgramSpecApplyConfiguration {
	if b.Resources == nil && len(entries) > 0 {
		b.Resources = make(map[string]ResourceApplyConfiguration, len(entries))
	}
	for k, v := range entries {
		b.Resources[k] = v
	}
	return b
}

// WithVariables puts the entries into the Variables field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Variables field,
// overwriting an existing map entries in Variables field with the same key.
func (b *ProgramSpecApplyConfiguration) WithVariables(entries map[string]apiextensionsv1.JSON) *ProgramSpecApplyConfiguration {
	if b.Variables == nil && len(entries) > 0 {
		b.Variables = make(map[string]apiextensionsv1.JSON, len(entries))
	}
	for k, v := range entries {
		b.Variables[k] = v
	}
	return b
}

// WithOutputs puts the entries into the Outputs field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Outputs field,
// overwriting an existing map entries in Outputs field with the same key.
func (b *ProgramSpecApplyConfiguration) WithOutputs(entries map[string]apiextensionsv1.JSON) *ProgramSpecApplyConfiguration {
	if b.Outputs == nil && len(entries) > 0 {
		b.Outputs = make(map[string]apiextensionsv1.JSON, len(entries))
	}
	for k, v := range entries {
		b.Outputs[k] = v
	}
	return b
}

// WithPackages puts the entries into the Packages field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Packages field,
// overwriting an existing map entries in Packages field with the same key.
func (b *ProgramSpecApplyConfiguration) WithPackages(entries map[string]string) *ProgramSpecApplyConfiguration {
	if b.Packages == nil && len(entries) > 0 {
		b.Packages = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.Packages[k] = v
	}
	return b
}
