// Copyright 2016-2025, Pulumi Corporation.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	apiextensionsv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
)

// ResourceApplyConfiguration represents a declarative configuration of the Resource type for use
// with apply.
type ResourceApplyConfiguration struct {
	Type       *string                         `json:"type,omitempty"`
	Properties map[string]apiextensionsv1.JSON `json:"properties,omitempty"`
	Options    *OptionsApplyConfiguration      `json:"options,omitempty"`
	Get        *GetterApplyConfiguration       `json:"get,omitempty"`
}

// ResourceApplyConfiguration constructs a declarative configuration of the Resource type for use with
// apply.
func Resource() *ResourceApplyConfiguration {
	return &ResourceApplyConfiguration{}
}

// WithType sets the Type field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Type field is set to the value of the last call.
func (b *ResourceApplyConfiguration) WithType(value string) *ResourceApplyConfiguration {
	b.Type = &value
	return b
}

// WithProperties puts the entries into the Properties field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Properties field,
// overwriting an existing map entries in Properties field with the same key.
func (b *ResourceApplyConfiguration) WithProperties(entries map[string]apiextensionsv1.JSON) *ResourceApplyConfiguration {
	if b.Properties == nil && len(entries) > 0 {
		b.Properties = make(map[string]apiextensionsv1.JSON, len(entries))
	}
	for k, v := range entries {
		b.Properties[k] = v
	}
	return b
}

// WithOptions sets the Options field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Options field is set to the value of the last call.
func (b *ResourceApplyConfiguration) WithOptions(value *OptionsApplyConfiguration) *ResourceApplyConfiguration {
	b.Options = value
	return b
}

// WithGet sets the Get field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Get field is set to the value of the last call.
func (b *ResourceApplyConfiguration) WithGet(value *GetterApplyConfiguration) *ResourceApplyConfiguration {
	b.Get = value
	return b
}
