apiVersion: v1
kind: Secret
metadata:
  name: pulumi-api-secret
type: Opaque
stringData:
  accessToken: "<REDACTED: PULUMI_ACCESS_TOKEN>"
---
apiVersion: pulumi.com/v1
kind: Stack
metadata:
  name: nginx-k8s-stack
spec:
  envRefs:
    PULUMI_ACCESS_TOKEN:
      type: Secret
      secret:
        name: pulumi-api-secret
        key: accessToken
  stack: <ACCOUNT_NAME>/k8s-nginx/dev
  projectRepo: https://github.com/pulumi/examples
  repoDir: /kubernetes-ts-nginx
  branch: "refs/heads/master"
  destroyOnFinalize: true
