# A service account named `default/pulumi` for the Pulumi workspace (execution environment).
# If your Pulumi program uses the Kubernetes resource provider, this service account will be used to 
# authenticate with the Kubernetes cluster.
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: default
  name: pulumi
