# coding=utf-8
# *** WARNING: this file was generated by crd2pulumi. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

SNAKE_TO_CAMEL_CASE_TABLE = {
    "access_token_secret": "accessTokenSecret",
    "api_version": "apiVersion",
    "destroy_on_finalize": "destroyOnFinalize",
    "env_secrets": "envSecrets",
    "expect_no_refresh_changes": "expectNoRefreshChanges",
    "git_auth_secret": "gitAuthSecret",
    "last_attempted_commit": "lastAttemptedCommit",
    "last_successful_commit": "lastSuccessfulCommit",
    "last_update": "lastUpdate",
    "project_repo": "projectRepo",
    "repo_dir": "repoDir",
    "retry_on_update_conflict": "retryOnUpdateConflict",
    "secrets_provider": "secretsProvider",
}

CAMEL_TO_SNAKE_CASE_TABLE = {
    "accessTokenSecret": "access_token_secret",
    "apiVersion": "api_version",
    "destroyOnFinalize": "destroy_on_finalize",
    "envSecrets": "env_secrets",
    "expectNoRefreshChanges": "expect_no_refresh_changes",
    "gitAuthSecret": "git_auth_secret",
    "lastAttemptedCommit": "last_attempted_commit",
    "lastSuccessfulCommit": "last_successful_commit",
    "lastUpdate": "last_update",
    "projectRepo": "project_repo",
    "repoDir": "repo_dir",
    "retryOnUpdateConflict": "retry_on_update_conflict",
    "secretsProvider": "secrets_provider",
}
