apiVersion: v1
kind: ServiceAccount
metadata:
  name: random-yaml-program
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: random-yaml-program:system:auth-delegator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: random-yaml-program
  namespace: default
---
apiVersion: pulumi.com/v1
kind: Stack
metadata:
  name: random-yaml-program
  namespace: default
spec:
  serviceAccountName: random-yaml-program
  programRef:
    name: random-yaml
  stack: random-yaml-program
  refresh: true
  destroyOnFinalize: true
  envRefs:
    PULUMI_ACCESS_TOKEN:
      type: Secret
      secret:
        name: pulumi-api-secret
        key: accessToken
  workspaceTemplate:
    spec:
      image: pulumi/pulumi:3.134.1-nonroot

