// Copyright 2016-2025, Pulumi Corporation.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// ConfigValueFromApplyConfiguration represents a declarative configuration of the ConfigValueFrom type for use
// with apply.
type ConfigValueFromApplyConfiguration struct {
	Env  *string `json:"env,omitempty"`
	Path *string `json:"path,omitempty"`
}

// ConfigValueFromApplyConfiguration constructs a declarative configuration of the ConfigValueFrom type for use with
// apply.
func ConfigValueFrom() *ConfigValueFromApplyConfiguration {
	return &ConfigValueFromApplyConfiguration{}
}

// WithEnv sets the Env field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Env field is set to the value of the last call.
func (b *ConfigValueFromApplyConfiguration) WithEnv(value string) *ConfigValueFromApplyConfiguration {
	b.Env = &value
	return b
}

// WithPath sets the Path field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Path field is set to the value of the last call.
func (b *ConfigValueFromApplyConfiguration) WithPath(value string) *ConfigValueFromApplyConfiguration {
	b.Path = &value
	return b
}
