// Copyright 2016-2025, Pulumi Corporation.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
)

// GitHubAppAuthApplyConfiguration represents a declarative configuration of the GitHubAppAuth type for use
// with apply.
type GitHubAppAuthApplyConfiguration struct {
	AppID          *v1.SecretKeySelector `json:"appID,omitempty"`
	InstallationID *v1.SecretKeySelector `json:"installationID,omitempty"`
	PrivateKey     *v1.SecretKeySelector `json:"privateKey,omitempty"`
}

// GitHubAppAuthApplyConfiguration constructs a declarative configuration of the GitHubAppAuth type for use with
// apply.
func GitHubAppAuth() *GitHubAppAuthApplyConfiguration {
	return &GitHubAppAuthApplyConfiguration{}
}

// WithAppID sets the AppID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AppID field is set to the value of the last call.
func (b *GitHubAppAuthApplyConfiguration) WithAppID(value v1.SecretKeySelector) *GitHubAppAuthApplyConfiguration {
	b.AppID = &value
	return b
}

// WithInstallationID sets the InstallationID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the InstallationID field is set to the value of the last call.
func (b *GitHubAppAuthApplyConfiguration) WithInstallationID(value v1.SecretKeySelector) *GitHubAppAuthApplyConfiguration {
	b.InstallationID = &value
	return b
}

// WithPrivateKey sets the PrivateKey field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PrivateKey field is set to the value of the last call.
func (b *GitHubAppAuthApplyConfiguration) WithPrivateKey(value v1.SecretKeySelector) *GitHubAppAuthApplyConfiguration {
	b.PrivateKey = &value
	return b
}
