// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.Pulumi.V1Alpha1
{

    /// <summary>
    /// StackStatus defines the observed state of Stack
    /// </summary>
    public class StackStatusArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// LastUpdate contains details of the status of the last update.
        /// </summary>
        [Input("lastUpdate")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Pulumi.V1Alpha1.StackStatusLastUpdateArgs>? LastUpdate { get; set; }

        [Input("outputs")]
        private InputMap<ImmutableDictionary<string, object>>? _outputs;

        /// <summary>
        /// Outputs contains the exported stack output variables resulting from a deployment.
        /// </summary>
        public InputMap<ImmutableDictionary<string, object>> Outputs
        {
            get => _outputs ?? (_outputs = new InputMap<ImmutableDictionary<string, object>>());
            set => _outputs = value;
        }

        public StackStatusArgs()
        {
        }
    }
}
