apiVersion: v1
kind: ServiceAccount
metadata:
  name: custom-source
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: custom-source:system:auth-delegator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: custom-source
  namespace: default
---
apiVersion: pulumi.com/v1
kind: Stack
metadata:
  name: custom-source
  namespace: default
spec:
  serviceAccountName: custom-source
  stack: dev
  refresh: true
  continueResyncOnCommitMatch: true
  resyncFrequencySeconds: 60
  destroyOnFinalize: true
  envRefs:
    PULUMI_ACCESS_TOKEN:
      type: Secret
      secret:
        name: pulumi-api-secret
        key: accessToken
  workspaceTemplate:
    spec:
      image: localhost:5000/pulumi-and-app:latest
      imagePullPolicy: IfNotPresent
      local:
        dir: /home/pulumi/examples/stack-readme-py
