# permissions to call TokenRequest API to impersonate the controller-manager account.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/name: pulumi-kubernetes-operator
    app.kubernetes.io/managed-by: kustomize
  name: token-request-role
rules:
- apiGroups:
  - ""
  resources:
  - serviceaccounts/token
  resourceNames:
  - controller-manager
  verbs:
  - create
