apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: pulumi-kubernetes-operator
    app.kubernetes.io/managed-by: kustomize
  name: token-request-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: token-request-role
subjects:
  - kind: ServiceAccount
    name: controller-manager
    namespace: pulumi-kubernetes-operator
