apiVersion: v1
kind: ServiceAccount
metadata:
  name: random-yaml-flux
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: random-yaml-flux:system:auth-delegator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: random-yaml-flux
  namespace: default
---
apiVersion: pulumi.com/v1
kind: Stack
metadata:
  name: random-yaml-flux
  namespace: default
spec:
  serviceAccountName: random-yaml-flux
  fluxSource:
    sourceRef:
      apiVersion: source.toolkit.fluxcd.io/v1
      kind: GitRepository
      name: pulumi-examples
    dir: random-yaml/
  stack: random-yaml-flux
  refresh: true
  destroyOnFinalize: true
  envRefs:
    PULUMI_ACCESS_TOKEN:
      type: Secret
      secret:
        name: pulumi-api-secret
        key: accessToken
  workspaceTemplate:
    spec:
      image: pulumi/pulumi:3.197.0-nonroot

