apiVersion: v1
kind: ServiceAccount
metadata:
  name: random-yaml-git
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: random-yaml-git:system:auth-delegator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: random-yaml-git
  namespace: default
---
apiVersion: pulumi.com/v1
kind: Stack
metadata:
  name: random-yaml-git
  namespace: default
spec:
  serviceAccountName: random-yaml-git
  projectRepo: https://github.com/pulumi/examples
  branch: master
  shallow: true
  repoDir: random-yaml/
  stack: random-yaml-git
  refresh: true
  destroyOnFinalize: true
  envRefs:
    PULUMI_ACCESS_TOKEN:
      type: Secret
      secret:
        name: pulumi-api-secret
        key: accessToken
  workspaceTemplate:
    spec:
      image: pulumi/pulumi:3.198.0-nonroot

