// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Crds.Pulumi.V1Alpha1
{
    /// <summary>
    /// Stack is the Schema for the stacks API
    /// </summary>
    public partial class Stack : KubernetesResource
    {
        [Output("apiVersion")]
        public Output<string> ApiVersion { get; private set; } = null!;

        [Output("kind")]
        public Output<string> Kind { get; private set; } = null!;

        [Output("metadata")]
        public Output<Pulumi.Kubernetes.Types.Outputs.Meta.V1.ObjectMeta> Metadata { get; private set; } = null!;

        /// <summary>
        /// StackSpec defines the desired state of Pulumi Stack being managed by this operator.
        /// </summary>
        [Output("spec")]
        public Output<Pulumi.Kubernetes.Types.Outputs.Pulumi.V1Alpha1.StackSpec> Spec { get; private set; } = null!;

        /// <summary>
        /// StackStatus defines the observed state of Stack
        /// </summary>
        [Output("status")]
        public Output<Pulumi.Kubernetes.Types.Outputs.Pulumi.V1Alpha1.StackStatus> Status { get; private set; } = null!;


        /// <summary>
        /// Create a Stack resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Stack(string name, Pulumi.Kubernetes.Types.Inputs.Pulumi.V1Alpha1.StackArgs? args = null, CustomResourceOptions? options = null)
            : base("kubernetes:pulumi.com/v1alpha1:Stack", name, MakeArgs(args), MakeResourceOptions(options, ""))
        {
        }
        internal Stack(string name, ImmutableDictionary<string, object?> dictionary, CustomResourceOptions? options = null)
            : base("kubernetes:pulumi.com/v1alpha1:Stack", name, new DictionaryResourceArgs(dictionary), MakeResourceOptions(options, ""))
        {
        }

        private Stack(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("kubernetes:pulumi.com/v1alpha1:Stack", name, null, MakeResourceOptions(options, id))
        {
        }

        private static Pulumi.Kubernetes.Types.Inputs.Pulumi.V1Alpha1.StackArgs? MakeArgs(Pulumi.Kubernetes.Types.Inputs.Pulumi.V1Alpha1.StackArgs? args)
        {
            args ??= new Pulumi.Kubernetes.Types.Inputs.Pulumi.V1Alpha1.StackArgs();
            args.ApiVersion = "pulumi.com/v1alpha1";
            args.Kind = "Stack";
            return args;
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Stack resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Stack Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new Stack(name, id, options);
        }
    }
}
namespace Pulumi.Kubernetes.Types.Inputs.Pulumi.V1Alpha1
{

    public class StackArgs : Pulumi.ResourceArgs
    {
        [Input("apiVersion")]
        public Input<string>? ApiVersion { get; set; }

        [Input("kind")]
        public Input<string>? Kind { get; set; }

        [Input("metadata")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Meta.V1.ObjectMetaArgs>? Metadata { get; set; }

        /// <summary>
        /// StackSpec defines the desired state of Pulumi Stack being managed by this operator.
        /// </summary>
        [Input("spec")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Pulumi.V1Alpha1.StackSpecArgs>? Spec { get; set; }

        /// <summary>
        /// StackStatus defines the observed state of Stack
        /// </summary>
        [Input("status")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Pulumi.V1Alpha1.StackStatusArgs>? Status { get; set; }

        public StackArgs()
        {
        }
    }
}
