apiVersion: v1
kind: Secret
metadata:
  name: aws-creds-secret
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "<REDACTED: AWS_ACCESS_KEY_ID>"
  AWS_SECRET_ACCESS_KEY: "<REDACTED: AWS_SECRET_ACCESS_KEY>"
  AWS_SESSION_TOKEN: "<REDACTED: AWS_SESSION_TOKEN>"
---
apiVersion: pulumi.com/v1
kind: Stack
metadata:
  name: nginx-k8s-stack
spec:
  backend: "s3://<S3 BUCKET>"
  secretsProvider: "awskms:///<KMS KEY ARN>?region=<REGION>"
  envRefs:
    AWS_DEFAULT_REGION:
      type: Literal
      literal:
        value: <REGION>
    AWS_ACCESS_KEY_ID:
      type: Secret
      secret:
        name: aws-creds-secret
        key: AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY:
      type: Secret
      secret:
        name: aws-creds-secret
        key: AWS_SECRET_ACCESS_KEY
    AWS_SESION_TOKEN:
      type: Secret
      secret:
        name: aws-creds-secret
        key: AWS_SESSION_TOKEN
  stack: "s3backend.nginx.dev"
  projectRepo: https://github.com/metral/pulumi-nginx
  branch: "refs/heads/master"
  destroyOnFinalize: true
