apiVersion: v1
kind: ServiceAccount
metadata:
  name: random-yaml
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: random-yaml:system:auth-delegator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: random-yaml
  namespace: default
---
apiVersion: pulumi.com/v1
kind: Stack
metadata:
  name: random-yaml
  namespace: default
spec:
  serviceAccountName: random-yaml
  fluxSource:
    sourceRef:
      apiVersion: source.toolkit.fluxcd.io/v1
      kind: GitRepository
      name: pulumi-examples
    dir: random-yaml/
  stack: dev
  refresh: true
  continueResyncOnCommitMatch: false
  resyncFrequencySeconds: 60
  destroyOnFinalize: true
  config:
    aws:region: us-west-1
  envRefs:
    PULUMI_ACCESS_TOKEN:
      type: Secret
      secret:
        name: pulumi-api-secret
        key: accessToken
  workspaceTemplate:
    spec:
      image: pulumi/pulumi:3.134.1-nonroot

