---
permissions: write-all # Equivalent to default permissions plus id-token: write
env:
  ESC_ACTION_OIDC_AUTH: true
  ESC_ACTION_OIDC_ORGANIZATION: pulumi
  ESC_ACTION_OIDC_REQUESTED_TOKEN_TYPE: urn:pulumi:token-type:access_token:organization
  ESC_ACTION_ENVIRONMENT: imports/github-secrets
  ESC_ACTION_EXPORT_ENVIRONMENT_VARIABLES: false
name: Command Dispatch for testing
on:
  issue_comment:
    types: [created, edited]

jobs:
  command-dispatch-for-testing:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch secrets from ESC
        id: esc-secrets
        uses: pulumi/esc-action@v1
      - uses: actions/checkout@v2
      - name: Run Build
        uses: peter-evans/slash-command-dispatch@v2
        with:
          token: ${{ steps.esc-secrets.outputs.PULUMI_BOT_TOKEN }}
          reaction-token: ${{ secrets.GITHUB_TOKEN }}
          commands: run-acceptance-tests
          permission: write
          issue-type: pull-request
          repository: pulumi/pulumi-kubernetes-operator
