---
name: pull-request
"on":
  pull_request_target:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19.X
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.50
          # Optional: working directory, useful for monorepos
          # working-directory: somedir

          # Optional: golangci-lint command line arguments.
          # args: --issues-exit-code=0

          # Optional: show only new issues if it's a pull request. The default value is `false`.
          # only-new-issues: true
  comment-on-pr:
    if: github.event.pull_request.head.repo.full_name != github.repository
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@main
        with:
          message: |
            PR is now waiting for a maintainer to run the acceptance tests. This PR will only perform build and linting.
            **Note for the maintainer:** To run the acceptance tests, please comment */run-acceptance-tests* on the PR
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
Expect(err):
  NotTo(HaveOccurred()):
