---
name: Pulumi Kubernetes Operator PR Builds
on:
  push:
    branches:
      - v2
  pull_request:
    branches:
      - v2
env:
  PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  PULUMI_BOT_TOKEN: ${{ secrets.PULUMI_BOT_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.x
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser-pro
          # 'latest', 'nightly', or a semver
          version: "~> v2"
          args: release --snapshot --clean --skip=docker

  unit-tests:
    runs-on: ubuntu-latest
    name: Unit tests
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.x
      - name: Install Pulumi
        uses: pulumi/actions@v5
      - name: Run Tests (Agent)
        run: make -C agent test
      - name: Run Tests (Operator)
        run: make -C operator test
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: agent/coverage.out,operator/coverage.out
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  e2e-tests:
    runs-on: ubuntu-latest
    name: E2E tests
    steps:
      - name: Setup cluster
        uses: helm/kind-action@v1
        with:
          cluster_name: kind
          node_image: kindest/node:v1.31.0
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.x
      - name: Run tests
        run: make -C operator test-e2e
