# coding=utf-8
# *** WARNING: this file was generated by crd2pulumi. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union
from ... import _utilities, _tables
from . import outputs

__all__ = [
    'StackSpec',
    'StackStatus',
    'StackStatusLastUpdate',
]

@pulumi.output_type
class StackSpec(dict):
    """
    StackSpec defines the desired state of Pulumi Stack being managed by this operator.
    """
    def __init__(__self__, *,
                 project_repo: str,
                 stack: str,
                 access_token_secret: Optional[str] = None,
                 backend: Optional[str] = None,
                 branch: Optional[str] = None,
                 commit: Optional[str] = None,
                 config: Optional[Mapping[str, str]] = None,
                 destroy_on_finalize: Optional[bool] = None,
                 env_secrets: Optional[Sequence[str]] = None,
                 envs: Optional[Sequence[str]] = None,
                 expect_no_refresh_changes: Optional[bool] = None,
                 git_auth_secret: Optional[str] = None,
                 refresh: Optional[bool] = None,
                 repo_dir: Optional[str] = None,
                 retry_on_update_conflict: Optional[bool] = None,
                 secrets: Optional[Mapping[str, str]] = None,
                 secrets_provider: Optional[str] = None):
        """
        StackSpec defines the desired state of Pulumi Stack being managed by this operator.
        :param str project_repo: ProjectRepo is the git source control repository from which we fetch the project code and configuration.
        :param str stack: Stack is the fully qualified name of the stack to deploy (<org>/<stack>).
        :param str access_token_secret: (optional) AccessTokenSecret is the name of a secret containing the PULUMI_ACCESS_TOKEN for Pulumi access.
        :param str backend: (optional) Backend is an optional backend URL to use for all Pulumi operations. Examples:   - Pulumi Service:              "https://app.pulumi.com" (default)   - Self-managed Pulumi Service: "https://pulumi.acmecorp.com"   - Local:                       "file://./einstein"   - AWS:                         "s3://<my-pulumi-state-bucket>"   - Azure:                       "azblob://<my-pulumi-state-bucket>"   - GCP:                         "gs://<my-pulumi-state-bucket>" See: https://www.pulumi.com/docs/intro/concepts/state/
        :param str branch: (optional) Branch is the branch name to deploy, either the simple or fully qualified ref name. This is mutually exclusive with the Commit setting. If both are empty, the `master` branch is deployed.
        :param str commit: (optional) Commit is the hash of the commit to deploy. If used, HEAD will be in detached mode. This is mutually exclusive with the Branch setting. If both are empty, the `master` branch is deployed.
        :param Mapping[str, str] config: (optional) Config is the configuration for this stack, which can be optionally specified inline. If this is omitted, configuration is assumed to be checked in and taken from the source repository.
        :param bool destroy_on_finalize: (optional) DestroyOnFinalize can be set to true to destroy the stack completely upon deletion of the CRD.
        :param Sequence[str] env_secrets: (optional) SecretEnvs is an optional array of secret names containing environment variables to set.
        :param Sequence[str] envs: (optional) Envs is an optional array of config maps containing environment variables to set.
        :param bool expect_no_refresh_changes: (optional) ExpectNoRefreshChanges can be set to true if a stack is not expected to have changes during a refresh before the update is run. This could occur, for example, is a resource's state is changing outside of Pulumi (e.g., metadata, timestamps).
        :param str git_auth_secret: (optional) GitAuthSecret is the the name of a secret containing an authentication option for the git repository. There are 3 different authentication options:   * Personal access token   * SSH private key (and it's optional password)   * Basic auth username and password Only 1 authentication path is valid.
        :param bool refresh: (optional) Refresh can be set to true to refresh the stack before it is updated.
        :param str repo_dir: (optional) RepoDir is the directory to work from in the project's source repository where Pulumi.yaml is located. It is used in case Pulumi.yaml is not in the project source root.
        :param bool retry_on_update_conflict: (optional) RetryOnUpdateConflict issues a stack update retry reconciliation loop in the event that the update hits a HTTP 409 conflict due to another update in progress. This is only recommended if you are sure that the stack updates are idempotent, and if you are willing to accept retry loops until all spawned retries succeed. This will also create a more populated, and randomized activity timeline for the stack in the Pulumi Service.
        :param Mapping[str, str] secrets: (optional) Secrets is the secret configuration for this stack, which can be optionally specified inline. If this is omitted, secrets configuration is assumed to be checked in and taken from the source repository.
        :param str secrets_provider: (optional) SecretsProvider is used to initialize a Stack with alternative encryption. Examples:   - AWS:   "awskms://arn:aws:kms:us-east-1:111122223333:key/1234abcd-12ab-34bc-56ef-1234567890ab?region=us-east-1"   - Azure: "azurekeyvault://acmecorpvault.vault.azure.net/keys/mykeyname"   - GCP:   "gcpkms://projects/MYPROJECT/locations/MYLOCATION/keyRings/MYKEYRING/cryptoKeys/MYKEY" See: https://www.pulumi.com/docs/intro/concepts/config/#initializing-a-stack-with-alternative-encryption
        """
        pulumi.set(__self__, "project_repo", project_repo)
        pulumi.set(__self__, "stack", stack)
        if access_token_secret is not None:
            pulumi.set(__self__, "access_token_secret", access_token_secret)
        if backend is not None:
            pulumi.set(__self__, "backend", backend)
        if branch is not None:
            pulumi.set(__self__, "branch", branch)
        if commit is not None:
            pulumi.set(__self__, "commit", commit)
        if config is not None:
            pulumi.set(__self__, "config", config)
        if destroy_on_finalize is not None:
            pulumi.set(__self__, "destroy_on_finalize", destroy_on_finalize)
        if env_secrets is not None:
            pulumi.set(__self__, "env_secrets", env_secrets)
        if envs is not None:
            pulumi.set(__self__, "envs", envs)
        if expect_no_refresh_changes is not None:
            pulumi.set(__self__, "expect_no_refresh_changes", expect_no_refresh_changes)
        if git_auth_secret is not None:
            pulumi.set(__self__, "git_auth_secret", git_auth_secret)
        if refresh is not None:
            pulumi.set(__self__, "refresh", refresh)
        if repo_dir is not None:
            pulumi.set(__self__, "repo_dir", repo_dir)
        if retry_on_update_conflict is not None:
            pulumi.set(__self__, "retry_on_update_conflict", retry_on_update_conflict)
        if secrets is not None:
            pulumi.set(__self__, "secrets", secrets)
        if secrets_provider is not None:
            pulumi.set(__self__, "secrets_provider", secrets_provider)

    @property
    @pulumi.getter(name="projectRepo")
    def project_repo(self) -> str:
        """
        ProjectRepo is the git source control repository from which we fetch the project code and configuration.
        """
        return pulumi.get(self, "project_repo")

    @property
    @pulumi.getter
    def stack(self) -> str:
        """
        Stack is the fully qualified name of the stack to deploy (<org>/<stack>).
        """
        return pulumi.get(self, "stack")

    @property
    @pulumi.getter(name="accessTokenSecret")
    def access_token_secret(self) -> Optional[str]:
        """
        (optional) AccessTokenSecret is the name of a secret containing the PULUMI_ACCESS_TOKEN for Pulumi access.
        """
        return pulumi.get(self, "access_token_secret")

    @property
    @pulumi.getter
    def backend(self) -> Optional[str]:
        """
        (optional) Backend is an optional backend URL to use for all Pulumi operations. Examples:   - Pulumi Service:              "https://app.pulumi.com" (default)   - Self-managed Pulumi Service: "https://pulumi.acmecorp.com"   - Local:                       "file://./einstein"   - AWS:                         "s3://<my-pulumi-state-bucket>"   - Azure:                       "azblob://<my-pulumi-state-bucket>"   - GCP:                         "gs://<my-pulumi-state-bucket>" See: https://www.pulumi.com/docs/intro/concepts/state/
        """
        return pulumi.get(self, "backend")

    @property
    @pulumi.getter
    def branch(self) -> Optional[str]:
        """
        (optional) Branch is the branch name to deploy, either the simple or fully qualified ref name. This is mutually exclusive with the Commit setting. If both are empty, the `master` branch is deployed.
        """
        return pulumi.get(self, "branch")

    @property
    @pulumi.getter
    def commit(self) -> Optional[str]:
        """
        (optional) Commit is the hash of the commit to deploy. If used, HEAD will be in detached mode. This is mutually exclusive with the Branch setting. If both are empty, the `master` branch is deployed.
        """
        return pulumi.get(self, "commit")

    @property
    @pulumi.getter
    def config(self) -> Optional[Mapping[str, str]]:
        """
        (optional) Config is the configuration for this stack, which can be optionally specified inline. If this is omitted, configuration is assumed to be checked in and taken from the source repository.
        """
        return pulumi.get(self, "config")

    @property
    @pulumi.getter(name="destroyOnFinalize")
    def destroy_on_finalize(self) -> Optional[bool]:
        """
        (optional) DestroyOnFinalize can be set to true to destroy the stack completely upon deletion of the CRD.
        """
        return pulumi.get(self, "destroy_on_finalize")

    @property
    @pulumi.getter(name="envSecrets")
    def env_secrets(self) -> Optional[Sequence[str]]:
        """
        (optional) SecretEnvs is an optional array of secret names containing environment variables to set.
        """
        return pulumi.get(self, "env_secrets")

    @property
    @pulumi.getter
    def envs(self) -> Optional[Sequence[str]]:
        """
        (optional) Envs is an optional array of config maps containing environment variables to set.
        """
        return pulumi.get(self, "envs")

    @property
    @pulumi.getter(name="expectNoRefreshChanges")
    def expect_no_refresh_changes(self) -> Optional[bool]:
        """
        (optional) ExpectNoRefreshChanges can be set to true if a stack is not expected to have changes during a refresh before the update is run. This could occur, for example, is a resource's state is changing outside of Pulumi (e.g., metadata, timestamps).
        """
        return pulumi.get(self, "expect_no_refresh_changes")

    @property
    @pulumi.getter(name="gitAuthSecret")
    def git_auth_secret(self) -> Optional[str]:
        """
        (optional) GitAuthSecret is the the name of a secret containing an authentication option for the git repository. There are 3 different authentication options:   * Personal access token   * SSH private key (and it's optional password)   * Basic auth username and password Only 1 authentication path is valid.
        """
        return pulumi.get(self, "git_auth_secret")

    @property
    @pulumi.getter
    def refresh(self) -> Optional[bool]:
        """
        (optional) Refresh can be set to true to refresh the stack before it is updated.
        """
        return pulumi.get(self, "refresh")

    @property
    @pulumi.getter(name="repoDir")
    def repo_dir(self) -> Optional[str]:
        """
        (optional) RepoDir is the directory to work from in the project's source repository where Pulumi.yaml is located. It is used in case Pulumi.yaml is not in the project source root.
        """
        return pulumi.get(self, "repo_dir")

    @property
    @pulumi.getter(name="retryOnUpdateConflict")
    def retry_on_update_conflict(self) -> Optional[bool]:
        """
        (optional) RetryOnUpdateConflict issues a stack update retry reconciliation loop in the event that the update hits a HTTP 409 conflict due to another update in progress. This is only recommended if you are sure that the stack updates are idempotent, and if you are willing to accept retry loops until all spawned retries succeed. This will also create a more populated, and randomized activity timeline for the stack in the Pulumi Service.
        """
        return pulumi.get(self, "retry_on_update_conflict")

    @property
    @pulumi.getter
    def secrets(self) -> Optional[Mapping[str, str]]:
        """
        (optional) Secrets is the secret configuration for this stack, which can be optionally specified inline. If this is omitted, secrets configuration is assumed to be checked in and taken from the source repository.
        """
        return pulumi.get(self, "secrets")

    @property
    @pulumi.getter(name="secretsProvider")
    def secrets_provider(self) -> Optional[str]:
        """
        (optional) SecretsProvider is used to initialize a Stack with alternative encryption. Examples:   - AWS:   "awskms://arn:aws:kms:us-east-1:111122223333:key/1234abcd-12ab-34bc-56ef-1234567890ab?region=us-east-1"   - Azure: "azurekeyvault://acmecorpvault.vault.azure.net/keys/mykeyname"   - GCP:   "gcpkms://projects/MYPROJECT/locations/MYLOCATION/keyRings/MYKEYRING/cryptoKeys/MYKEY" See: https://www.pulumi.com/docs/intro/concepts/config/#initializing-a-stack-with-alternative-encryption
        """
        return pulumi.get(self, "secrets_provider")

    def _translate_property(self, prop):
        return _tables.CAMEL_TO_SNAKE_CASE_TABLE.get(prop) or prop


@pulumi.output_type
class StackStatus(dict):
    """
    StackStatus defines the observed state of Stack
    """
    def __init__(__self__, *,
                 last_update: Optional['outputs.StackStatusLastUpdate'] = None,
                 outputs: Optional[Mapping[str, Mapping[str, Any]]] = None):
        """
        StackStatus defines the observed state of Stack
        :param 'StackStatusLastUpdateArgs' last_update: LastUpdate contains details of the status of the last update.
        :param Mapping[str, Mapping[str, Any]] outputs: Outputs contains the exported stack output variables resulting from a deployment.
        """
        if last_update is not None:
            pulumi.set(__self__, "last_update", last_update)
        if outputs is not None:
            pulumi.set(__self__, "outputs", outputs)

    @property
    @pulumi.getter(name="lastUpdate")
    def last_update(self) -> Optional['outputs.StackStatusLastUpdate']:
        """
        LastUpdate contains details of the status of the last update.
        """
        return pulumi.get(self, "last_update")

    @property
    @pulumi.getter
    def outputs(self) -> Optional[Mapping[str, Mapping[str, Any]]]:
        """
        Outputs contains the exported stack output variables resulting from a deployment.
        """
        return pulumi.get(self, "outputs")

    def _translate_property(self, prop):
        return _tables.CAMEL_TO_SNAKE_CASE_TABLE.get(prop) or prop


@pulumi.output_type
class StackStatusLastUpdate(dict):
    """
    LastUpdate contains details of the status of the last update.
    """
    def __init__(__self__, *,
                 last_attempted_commit: Optional[str] = None,
                 last_successful_commit: Optional[str] = None,
                 permalink: Optional[str] = None,
                 state: Optional[str] = None):
        """
        LastUpdate contains details of the status of the last update.
        :param str last_attempted_commit: Last commit attempted
        :param str last_successful_commit: Last commit successfully applied
        :param str permalink: Permalink is the Pulumi Console URL of the stack operation.
        :param str state: State is the state of the stack update - one of `succeeded` or `failed`
        """
        if last_attempted_commit is not None:
            pulumi.set(__self__, "last_attempted_commit", last_attempted_commit)
        if last_successful_commit is not None:
            pulumi.set(__self__, "last_successful_commit", last_successful_commit)
        if permalink is not None:
            pulumi.set(__self__, "permalink", permalink)
        if state is not None:
            pulumi.set(__self__, "state", state)

    @property
    @pulumi.getter(name="lastAttemptedCommit")
    def last_attempted_commit(self) -> Optional[str]:
        """
        Last commit attempted
        """
        return pulumi.get(self, "last_attempted_commit")

    @property
    @pulumi.getter(name="lastSuccessfulCommit")
    def last_successful_commit(self) -> Optional[str]:
        """
        Last commit successfully applied
        """
        return pulumi.get(self, "last_successful_commit")

    @property
    @pulumi.getter
    def permalink(self) -> Optional[str]:
        """
        Permalink is the Pulumi Console URL of the stack operation.
        """
        return pulumi.get(self, "permalink")

    @property
    @pulumi.getter
    def state(self) -> Optional[str]:
        """
        State is the state of the stack update - one of `succeeded` or `failed`
        """
        return pulumi.get(self, "state")

    def _translate_property(self, prop):
        return _tables.CAMEL_TO_SNAKE_CASE_TABLE.get(prop) or prop


